// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkidD9iuDHlXGQB9RfIL-_TNmm1-UCAiU',
    appId: '1:206828164316:web:182fda15c1836ef260d019',
    messagingSenderId: '206828164316',
    projectId: 'taskmanagement-3efe7',
    authDomain: 'taskmanagement-3efe7.firebaseapp.com',
    storageBucket: 'taskmanagement-3efe7.firebasestorage.app',
    measurementId: 'G-8N3GS9T33S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvdJaLZqq3YgMEG-Wsj6dvljnmgqQkCeg',
    appId: '1:206828164316:android:1dbbc0f5b077952960d019',
    messagingSenderId: '206828164316',
    projectId: 'taskmanagement-3efe7',
    storageBucket: 'taskmanagement-3efe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9QnUDwRFg5GAZhb8mxhgO7G9OrSYmO10',
    appId: '1:206828164316:ios:97973d7a80a55a4260d019',
    messagingSenderId: '206828164316',
    projectId: 'taskmanagement-3efe7',
    storageBucket: 'taskmanagement-3efe7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
